# -*- mode: ruby -*-
# vi: set ft=ruby :


# Server Node (mpaganiS): 
# This is the machine where the K3s server is running. 
# It hosts the control plane components, including etcd, 
# API server, controller manager, and scheduler. 
# The server node is responsible for managing the overall 
# state of the cluster.

# Worker Node (mpaganiSW): 
# This is a machine that runs workloads (containers) 
# as instructed by the control plane. 
# Worker nodes don't have the full control plane 
# components but play a role in executing and managing 
# the applications.

# Control Machine (or Management Machine): 
# This is the machine where you have kubectl installed. 
# with network connectivity to the K3s cluster. 
# The control machine is responsible for interacting 
# with the Kubernetes API server on the server node. 

# be sure that these packages are installes:    sudo apt install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager
  

Vagrant.configure("2") do |config|
  # config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "mpaganiS" do |server|
    # server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = "mpaganiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh", privileged: true, args: ["--debug"]
   end

  config.vm.define "mpaganiSW" do |worker|
    # worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = "mpaganiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh", privileged: true, args: ["--debug"]
  end
end