SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

SERVER_HOSTNAME = "mpaganiS"
WORKER_HOSTNAME = "mpaganiSW"

IMAGE = "generic/alpine311"

MEMORY = "1024"
CPUS = 1

Vagrant.configure("2") do |config|

  config.vm.box = IMAGE
  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
  end

  [SERVER_HOSTNAME, WORKER_HOSTNAME].each do |hostname|
    config.vm.define hostname do |node|
      node.vm.hostname = hostname
      node.vm.synced_folder ".", "/vagrant"
      node.vm.provision "shell", privileged: true, path: "scripts/#{hostname.downcase}.sh", args: [SERVER_IP, WORKER_IP]
      node.vm.network "private_network", ip: (hostname == SERVER_HOSTNAME ? SERVER_IP : WORKER_IP)
    end
  end
end
