# In this Kubernetes manifest we define 3 services (app1, app2, app3) of type BodePort
# Each service exposes port 80 on the host and directs traffic to port 8080 on the selected pods 
# with corresponding labels (app-1, app-2, and app-3).

{{- range $i, $appName := (list "app1" "app2" "app3") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
spec:
  selector:
    app: {{ $appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
{{- end }}
